apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: orderservice
  name: orderservice
spec:
  ports:
  - port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: orderservice
status:
  loadBalancer: {}