apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: paymentservice
  name: paymentservice
spec:
  ports:
  - port: 4002
    protocol: TCP
    targetPort: 4002
  selector:
    app: paymentservice
status:
  loadBalancer: {}