apiVersion : apps/v1
kind: Deployment
metadata:
  name: "ctsecluster-b88c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "ctsecluster-b88c"
  template:
    metadata:
      labels:
        app: "ctsecluster-b88c"
    spec:
      containers:
        - name: "ctsecluster-b88c"
          image: "25330.azurecr.io/ctsecluster"
          ports:
          - containerPort: 4002