apiVersion: v1
kind: Service
metadata:
    name: "ctsecluster-b88c"
    labels:
        app: "ctsecluster-b88c"
spec:
    type: LoadBalancer
    ports:
    - port: 4002
      targetPort: 4002
      protocol: TCP
      name: http
    selector:
        app: "ctsecluster-b88c"