apiVersion: v1
kind: Service
metadata:
    name: "ctsecluster-ceff"
    labels:
        app: "ctsecluster-ceff"
spec:
    type: LoadBalancer
    ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP
      name: http
    selector:
        app: "ctsecluster-ceff"