name: Docker Build Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
    
jobs:
  order_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - uses: actions/checkout@v3
      - name: run shell script
        run: echo commit hash is ${{ github.sha }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build order service
        run: |
          cd app/order_service
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/orderservice:${{ github.sha }}
      - name: Push order service
        run: docker push ${{ secrets.DOCKER_USERNAME }}/orderservice:${{ github.sha }}