name: Deploy payment service to Aks Cluster
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: 25330.azurecr.io
        username: ${{ secrets.acr_25330_username }}
        password: ${{ secrets.acr_25330_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app/payment_service" -f  "app/payment_service/Dockerfile" -t 25330.azurecr.io/ctsecluster:${{ github.sha }} --label dockerfile-path=app/payment_service/Dockerfile
        docker push 25330.azurecr.io/ctsecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_ctsecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: 25330.azurecr.io
        container-registry-username: ${{ secrets.acr_25330_username }}
        container-registry-password: ${{ secrets.acr_25330_password }}
        secret-name: ctseclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/deployment-payment.yml
          manifests/service-payment.yml
        images: |
          25330.azurecr.io/ctsecluster:${{ github.sha }}
        imagepullsecrets: |
          ctseclusterdockerauth
